[tasks.build]
command = "wasm-pack"
args = ["build", "--target", "nodejs"]

[tasks.npm-test]
dependencies = ["build"]
command = "node"
args = ["tests/integration-tests"]

[tasks.npm-publish]
dependencies = ["build", "npm-test"]
command = "wasm-pack"
args = ["publish"]